services:
  site-loomie:
    image: site-loomie
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true
