services:
  site-loomie:
    image: site-loomie
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - loomie-network

networks:
  loomie-network:
    external: true